# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JarvisGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisFrontEnd(object):
    def setupUi(self, JarvisFrontEnd):
        JarvisFrontEnd.setObjectName("JarvisFrontEnd")
        JarvisFrontEnd.resize(1548, 913)
        self.centralwidget = QtWidgets.QWidget(JarvisFrontEnd)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, -50, 1551, 951))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Iron Dad and Spider Son One-Shots.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.Run = QtWidgets.QPushButton(self.centralwidget)
        self.Run.setGeometry(QtCore.QRect(680, 670, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Run.setFont(font)
        self.Run.setStyleSheet("background-color: rgb(172, 255, 255);")
        self.Run.setAutoDefault(False)
        self.Run.setObjectName("Run")
        self.Run_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Run_2.setGeometry(QtCore.QRect(680, 750, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Run_2.setFont(font)
        self.Run_2.setStyleSheet("background-color: rgb(172, 255, 255);")
        self.Run_2.setAutoDefault(False)
        self.Run_2.setObjectName("Run_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(990, 30, 256, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgb(203, 250, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(1270, 30, 256, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background-color: rgb(203, 250, 255);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        JarvisFrontEnd.setCentralWidget(self.centralwidget)

        self.retranslateUi(JarvisFrontEnd)
        QtCore.QMetaObject.connectSlotsByName(JarvisFrontEnd)

    def retranslateUi(self, JarvisFrontEnd):
        _translate = QtCore.QCoreApplication.translate
        JarvisFrontEnd.setWindowTitle(_translate("JarvisFrontEnd", "MainWindow"))
        self.Run.setText(_translate("JarvisFrontEnd", "Run"))
        self.Run_2.setText(_translate("JarvisFrontEnd", "Terminate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisFrontEnd = QtWidgets.QMainWindow()
    ui = Ui_JarvisFrontEnd()
    ui.setupUi(JarvisFrontEnd)
    JarvisFrontEnd.show()
    sys.exit(app.exec_())
